### ISSUE TITLE
Documentation for changing subscription amount/offer incomplete

### ISSUE THREAD

**Issue by sklppr** [wengee-tek/paymill-documentation#19]
When updating a subscription, I can change both `amount` and `offer`.

I can use `amount_change_type` to indicate whether the change is temporary or permanent and `offer_change_type` to indicate how I want upgrades/downgrades to be handled.

**This information is not available in the new API reference,** i.e. parameters and values are documented but it’s not explained what they do.

The documentation in question is still available here:
- https://developers-v1.paymill.com/en-gb/subscription-v2-workflow/#update-sub-amount
- https://developers-v1.paymill.com/en-gb/subscription-v2-workflow/#update-sub-plan

**Comment by l0ck3** [comment]
@sklppr it seems that we're missing `subscription_amount_or_offer_update_not_allowed_one_day_before_charge` as well

**Comment by Hiroshitai** [comment]
Description for offer_change_type and amount_change_type has been added.
Issue closed
