### ISSUE TITLE
Wrong characters displayed in the PayPal section 

### ISSUE THREAD

**Issue by Emiliyana** [wengee-tek/paymill-documentation#36]
https://developers.paymill.com/guides/paypal/payments.html

See Screenshot
![paypaldocs](https://cloud.githubusercontent.com/assets/6206921/11342057/aee108f2-9205-11e5-8362-5dec7f173280.png)

**Comment by l0ck3** [comment]
Fixed by 984f1d01ea06c2ff7708ea03c1cdba405f47163c
